"""Release Evidence Closure Index — FINAL-PR-10++.

Claim boundary: final_pr_10_boundary_gated_release_operationalization_not_release_certification
candidate_only: true
app_owned_apply: true

Assembles an honest evidence closure index for all Odin subsystems.
Be honest: do not convert target-only into implemented.
FINAL-PR-11 remains deferred.
"""
from __future__ import annotations

import hashlib
import json

_CLAIM_BOUNDARY = "final_pr_10_boundary_gated_release_operationalization_not_release_certification"
_GENERATED_AT = "2026-01-01T00:00:00Z"


def _make_id(subsystem: str) -> str:
    digest = hashlib.sha256(f"evidence_closure_{subsystem}".encode()).hexdigest()[:16]
    return f"evidence_closure_{subsystem}_{digest}"


_SUBSYSTEMS = [
    {
        "subsystem": "Local Hub",
        "status": "implemented",
        "current_evidence": "odin/local_hub/server.py — running at 127.0.0.1:8765. GET /healthz, /status.json, UI, /operational-spine/*, /release/* endpoints.",
        "current_weakness": "No live model execution. No connected apps. No real provider execution.",
        "release_claim_allowed": "local_hub_exists_localhost_only",
        "release_claim_forbidden": "production_hub, live_model_hub, external_hub",
        "not_proven": ["production_readiness", "live_model_inference", "external_send"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "CLI",
        "status": "implemented",
        "current_evidence": "odin/cli.py — all validate-*, explain-*, run-*, release-preflight commands.",
        "current_weakness": "No live model execution via CLI.",
        "release_claim_allowed": "cli_exists_with_all_validators",
        "release_claim_forbidden": "cli_certified_production_ready",
        "not_proven": ["production_readiness", "live_model_inference"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Universal Work",
        "status": "implemented",
        "current_evidence": "odin/runtime/engine.py — run_universal_work_file(). ModelWorkPacket validation enforced.",
        "current_weakness": "No live model inference. Mock provider only.",
        "release_claim_allowed": "universal_work_candidate_only_operational",
        "release_claim_forbidden": "universal_work_live_model_execution",
        "not_proven": ["live_model_inference", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Handoff-First",
        "status": "implemented",
        "current_evidence": "odin/final_pr_ladder/compiler.py — compile_worker_packet_scaffold().",
        "current_weakness": "Handoff scaffold only; not a full Thor replacement.",
        "release_claim_allowed": "handoff_first_scaffold_exists",
        "release_claim_forbidden": "thor_replacement, full_handoff_runtime",
        "not_proven": ["production_readiness", "thor_parity"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Runtime Engine",
        "status": "implemented",
        "current_evidence": "odin/runtime/engine.py — candidate-only work execution engine.",
        "current_weakness": "No live model inference. Local runtime only.",
        "release_claim_allowed": "runtime_engine_candidate_only",
        "release_claim_forbidden": "production_runtime_certified",
        "not_proven": ["live_model_inference", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Operational Spine",
        "status": "implemented",
        "current_evidence": "odin/operational_spine/ — run_operational_spine(), ModelWorkPacket enforcement, small model route plan, Q-Shabang map, deferred system lift, provider seam.",
        "current_weakness": "No live model inference. Provider seam disabled by default.",
        "release_claim_allowed": "local_candidate_only_operational_spine_exists",
        "release_claim_forbidden": "live_model_spine, production_spine",
        "not_proven": ["live_model_inference", "production_readiness", "provider_execution"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Context Capsule",
        "status": "implemented",
        "current_evidence": "odin/operational_seed_spine/work_capsule.py — compile_work_capsule().",
        "current_weakness": "Capsule is a candidate structure, not live execution.",
        "release_claim_allowed": "context_capsule_candidate_only",
        "release_claim_forbidden": "live_context_execution",
        "not_proven": ["live_model_inference", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Artifact Lens",
        "status": "partial",
        "current_evidence": "odin/operational_seed_spine/ — partial lens structures.",
        "current_weakness": "Full artifact lens not yet fully implemented.",
        "release_claim_allowed": "artifact_lens_partial_exists",
        "release_claim_forbidden": "full_artifact_lens_implemented",
        "not_proven": ["full_artifact_lens", "production_readiness"],
        "future_pr_required": "Future PR for full artifact lens.",
    },
    {
        "subsystem": "Slot Forge",
        "status": "partial",
        "current_evidence": "odin/slots/ — partial slot structures.",
        "current_weakness": "Full slot forge not yet fully implemented.",
        "release_claim_allowed": "slot_forge_partial_exists",
        "release_claim_forbidden": "full_slot_forge_implemented",
        "not_proven": ["full_slot_forge", "production_readiness"],
        "future_pr_required": "Future PR for full slot forge.",
    },
    {
        "subsystem": "Gaptext",
        "status": "partial",
        "current_evidence": "odin/worklets/ — partial gaptext structures.",
        "current_weakness": "Full gaptext not yet fully implemented.",
        "release_claim_allowed": "gaptext_partial_exists",
        "release_claim_forbidden": "full_gaptext_implemented",
        "not_proven": ["full_gaptext", "production_readiness"],
        "future_pr_required": "Future PR for full gaptext.",
    },
    {
        "subsystem": "ModelWorkPacket",
        "status": "implemented",
        "current_evidence": "odin/operational_spine/modelworkpacket_builder.py — validate_modelworkpacket() enforced.",
        "current_weakness": "Validates packet structure; no live model execution.",
        "release_claim_allowed": "modelworkpacket_boundary_enforced",
        "release_claim_forbidden": "live_modelworkpacket_execution",
        "not_proven": ["live_model_inference", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Small Model Route Plan",
        "status": "implemented",
        "current_evidence": "odin/operational_spine/small_model_route_plan.py — route plan, not benchmark.",
        "current_weakness": "Route plan only. No empirical benchmark. No live execution.",
        "release_claim_allowed": "small_model_route_plan_exists",
        "release_claim_forbidden": "real_model_benchmark, live_model_inference",
        "not_proven": ["live_model_inference", "real_model_benchmark", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for live execution evidence.",
    },
    {
        "subsystem": "3B Roles",
        "status": "implemented_plan_only",
        "current_evidence": "odin/operational_spine/model_roles.py — 3B role definitions.",
        "current_weakness": "Role definitions only. No live 3B model execution.",
        "release_claim_allowed": "3b_roles_defined",
        "release_claim_forbidden": "live_3b_inference",
        "not_proven": ["live_3b_model_inference", "production_readiness"],
        "future_pr_required": "Provider activation for live 3B execution.",
    },
    {
        "subsystem": "7B Roles",
        "status": "implemented_plan_only",
        "current_evidence": "odin/operational_spine/model_roles.py — 7B role definitions.",
        "current_weakness": "Role definitions only. No live 7B model execution.",
        "release_claim_allowed": "7b_roles_defined",
        "release_claim_forbidden": "live_7b_inference",
        "not_proven": ["live_7b_model_inference", "production_readiness"],
        "future_pr_required": "Provider activation for live 7B execution.",
    },
    {
        "subsystem": "3B+7B Hybrid Roles",
        "status": "implemented_plan_only",
        "current_evidence": "odin/operational_spine/small_model_route_plan.py — hybrid route plans.",
        "current_weakness": "Hybrid plans only. No live hybrid execution. Not an empirical benchmark.",
        "release_claim_allowed": "hybrid_route_plan_exists",
        "release_claim_forbidden": "live_hybrid_inference, real_model_benchmark",
        "not_proven": ["live_hybrid_inference", "real_model_benchmark", "production_readiness"],
        "future_pr_required": "Provider activation for live hybrid execution.",
    },
    {
        "subsystem": "No-Model Precompute",
        "status": "implemented",
        "current_evidence": "odin/precompute/__init__.py — score_pre_llm_route() deterministic.",
        "current_weakness": "Deterministic only. No model involved.",
        "release_claim_allowed": "no_model_precompute_operational",
        "release_claim_forbidden": "model_inference_in_precompute",
        "not_proven": ["production_readiness"],
        "future_pr_required": "None for this scope.",
    },
    {
        "subsystem": "Semantic Cache",
        "status": "partial",
        "current_evidence": "odin/precompute/ — partial semantic cache structures.",
        "current_weakness": "Partial implementation only.",
        "release_claim_allowed": "semantic_cache_partial_exists",
        "release_claim_forbidden": "full_semantic_cache_implemented",
        "not_proven": ["full_semantic_cache", "production_readiness"],
        "future_pr_required": "Future PR for full semantic cache.",
    },
    {
        "subsystem": "Work Memory",
        "status": "partial",
        "current_evidence": "odin/storage/ — partial work memory structures.",
        "current_weakness": "Partial implementation only.",
        "release_claim_allowed": "work_memory_partial_exists",
        "release_claim_forbidden": "full_work_memory_implemented",
        "not_proven": ["full_work_memory", "production_readiness"],
        "future_pr_required": "Future PR for full work memory.",
    },
    {
        "subsystem": "QIRC",
        "status": "implemented",
        "current_evidence": "odin/qirc_core/ — local-only QIRC bus, channels, events.",
        "current_weakness": "Local only. Not app authority. Not public.",
        "release_claim_allowed": "qirc_local_coordination_exists",
        "release_claim_forbidden": "qirc_app_authority, public_qirc",
        "not_proven": ["production_readiness", "external_qirc"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Provider Probe",
        "status": "implemented",
        "current_evidence": "odin/providers/probe.py — provider probe checks readiness only.",
        "current_weakness": "Probe only. No provider execution.",
        "release_claim_allowed": "provider_probe_exists",
        "release_claim_forbidden": "provider_execution, live_model_inference",
        "not_proven": ["provider_execution", "live_model_inference", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Provider Seam",
        "status": "implemented_disabled_by_default",
        "current_evidence": "odin/operational_spine/provider_seam.py — disabled_by_default: true.",
        "current_weakness": "Disabled by default. No actual provider execution.",
        "release_claim_allowed": "local_provider_seam_disabled_by_default_confirmed",
        "release_claim_forbidden": "provider_execution, live_model_inference",
        "not_proven": ["provider_execution", "live_model_inference", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Execution Gate",
        "status": "implemented",
        "current_evidence": "odin/execution_gate/ — policy enforcement gate.",
        "current_weakness": "Policy only. No live model execution gate tested.",
        "release_claim_allowed": "execution_gate_policy_exists",
        "release_claim_forbidden": "execution_gate_live_model_certified",
        "not_proven": ["live_model_inference", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Operational Seed Spine",
        "status": "implemented",
        "current_evidence": "odin/operational_seed_spine/ — select_seed_route(), compile_work_capsule().",
        "current_weakness": "Seed route and capsule only. No live execution.",
        "release_claim_allowed": "operational_seed_spine_candidate_only",
        "release_claim_forbidden": "live_seed_execution",
        "not_proven": ["live_model_inference", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Field Selection Spine",
        "status": "implemented",
        "current_evidence": "odin/field_selection_spine/ — select_field_route(), select_field_route_from_seed_route().",
        "current_weakness": "Field selection only. No live execution.",
        "release_claim_allowed": "field_selection_spine_candidate_only",
        "release_claim_forbidden": "live_field_execution",
        "not_proven": ["live_model_inference", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Projection Candidate Spine",
        "status": "implemented",
        "current_evidence": "odin/projection_candidate_spine/ — build_projection_set_from_field_selection(), build_candidate_graph().",
        "current_weakness": "Projection set and candidate graph only. No live execution.",
        "release_claim_allowed": "projection_candidate_spine_candidate_only",
        "release_claim_forbidden": "live_projection_execution",
        "not_proven": ["live_model_inference", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Minicheck",
        "status": "partial",
        "current_evidence": "odin/quality/ — partial minicheck structures.",
        "current_weakness": "Partial implementation only.",
        "release_claim_allowed": "minicheck_partial_exists",
        "release_claim_forbidden": "full_minicheck_implemented",
        "not_proven": ["full_minicheck", "production_readiness"],
        "future_pr_required": "Future PR for full minicheck.",
    },
    {
        "subsystem": "Critic Cascade",
        "status": "implemented_plan_only",
        "current_evidence": "odin/operational_spine/orchestrator.py — critic_cascade_result in spine output.",
        "current_weakness": "Plan and structure only. No live critic execution.",
        "release_claim_allowed": "critic_cascade_plan_exists",
        "release_claim_forbidden": "live_critic_execution, quality_benchmark",
        "not_proven": ["live_critic_execution", "quality_benchmark", "production_readiness"],
        "future_pr_required": "Provider activation for live critic execution.",
    },
    {
        "subsystem": "Candidate Tournament",
        "status": "partial",
        "current_evidence": "odin/candidates/ — partial tournament structures.",
        "current_weakness": "Partial implementation only.",
        "release_claim_allowed": "candidate_tournament_partial_exists",
        "release_claim_forbidden": "full_candidate_tournament_implemented",
        "not_proven": ["full_candidate_tournament", "production_readiness"],
        "future_pr_required": "Future PR for full candidate tournament.",
    },
    {
        "subsystem": "Candidate Artifact",
        "status": "implemented",
        "current_evidence": "odin/candidates/ and odin/packets/ — candidate artifact structures.",
        "current_weakness": "Structure only. No live model generation.",
        "release_claim_allowed": "candidate_artifact_structure_exists",
        "release_claim_forbidden": "live_candidate_generation",
        "not_proven": ["live_model_inference", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Response Packet",
        "status": "implemented",
        "current_evidence": "odin/operational_spine/orchestrator.py — response packet in spine output.",
        "current_weakness": "Structure only. No live model response.",
        "release_claim_allowed": "response_packet_structure_exists",
        "release_claim_forbidden": "live_response_generation",
        "not_proven": ["live_model_inference", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Final Gate",
        "status": "implemented_plan_only",
        "current_evidence": "odin/operational_spine/orchestrator.py — final_gate_result in spine output.",
        "current_weakness": "Plan and structure only. No live gate execution with real candidates.",
        "release_claim_allowed": "final_gate_structure_exists",
        "release_claim_forbidden": "live_final_gate_certified",
        "not_proven": ["live_final_gate_execution", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Trace/Receipt/Proof",
        "status": "implemented",
        "current_evidence": "odin/proof_chain/ and odin/operational_spine/receipts.py — trace, receipt, proof chain.",
        "current_weakness": "Local traces and receipts only. No external proof.",
        "release_claim_allowed": "trace_receipt_proof_exists",
        "release_claim_forbidden": "external_proof, production_readiness",
        "not_proven": ["external_proof", "production_readiness", "security_certification"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "App-Owned Apply Boundary",
        "status": "implemented",
        "current_evidence": "All operational spine and work packets carry app_owned_apply: true.",
        "current_weakness": "Boundary asserted in code; not externally audited.",
        "release_claim_allowed": "app_owned_apply_boundary_enforced",
        "release_claim_forbidden": "app_apply, app_state_mutation",
        "not_proven": ["external_audit_of_apply_boundary", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Q-Shabang Runtime Map",
        "status": "implemented",
        "current_evidence": "odin/operational_spine/qshabang_runtime_map.py and odin/release_boundaries/qshabang_release_gate_map.py.",
        "current_weakness": "Map and gate definitions only. No live Q-Shabang model execution.",
        "release_claim_allowed": "qshabang_neutral_operationalization_confirmed",
        "release_claim_forbidden": "qshabang_runtime_authority, live_qshabang_execution",
        "not_proven": ["live_model_inference", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Bug6/Q7 Boundary Map",
        "status": "implemented",
        "current_evidence": "odin/release_boundaries/bug6_q7_operational_map.py — drift scanner definitions.",
        "current_weakness": "Scanner definitions only. No live autonomous scanning agent.",
        "release_claim_allowed": "bug6_q7_boundary_scanners_exist",
        "release_claim_forbidden": "scanner_as_agent_authority, live_autonomous_scanning",
        "not_proven": ["external_security_audit", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Artifact Currency",
        "status": "implemented",
        "current_evidence": "odin/release_boundaries/artifact_currency.py — currency classification.",
        "current_weakness": "Classification only. Not externally audited.",
        "release_claim_allowed": "artifact_currency_index_exists",
        "release_claim_forbidden": "external_currency_audit, production_readiness",
        "not_proven": ["external_artifact_audit", "production_readiness"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Release Evidence",
        "status": "implemented",
        "current_evidence": "odin/release_boundaries/evidence_closure.py — evidence closure index.",
        "current_weakness": "Evidence index only. Not external validation.",
        "release_claim_allowed": "release_evidence_closure_index_exists",
        "release_claim_forbidden": "external_release_validation, production_readiness",
        "not_proven": ["external_release_validation", "production_readiness", "security_certification"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
    {
        "subsystem": "Final Preflight",
        "status": "implemented",
        "current_evidence": "odin/release_boundaries/final_preflight.py — run_final_release_preflight().",
        "current_weakness": "Preflight check only. Not release certification.",
        "release_claim_allowed": "release_preflight_exists",
        "release_claim_forbidden": "release_certification, production_readiness, security_certification",
        "not_proven": ["release_certification", "production_readiness", "security_certification"],
        "future_pr_required": "FINAL-PR-11 for release closure.",
    },
]


def build_release_evidence_closure_index() -> dict:
    """Build the release evidence closure index.

    Assembles an honest, subsystem-by-subsystem evidence closure index.
    """
    subsystems = {}
    for sub in _SUBSYSTEMS:
        key = sub["subsystem"]
        subsystems[key] = dict(
            sub,
            evidence_closure_id=_make_id(key),
            candidate_only=True,
            claim_boundary=_CLAIM_BOUNDARY,
        )

    return json.loads(json.dumps({
        "artifact_kind": "odin_final_pr_10_release_evidence_closure_index",
        "candidate_only": True,
        "app_owned_apply": True,
        "claim_boundary": _CLAIM_BOUNDARY,
        "generated_at_utc": _GENERATED_AT,
        "subsystem_count": len(subsystems),
        "subsystems": subsystems,
        "not_proven": [
            "production_readiness",
            "live_model_inference",
            "app_state_mutation",
            "external_send_authority",
            "security_certification",
            "release_certification",
        ],
        "final_pr_11_remains_deferred": True,
    }))
