"""Model role definitions for FINAL-PR-09 Operational Spine.

Claim boundary: final_pr_09_operational_spine_candidate_kernel_not_live_model_proof_not_app_apply
candidate_only: true

Roles are schema/registry only — no model execution, no provider calls.
"""
from __future__ import annotations

CLAIM_BOUNDARY = "final_pr_09_operational_spine_candidate_kernel_not_live_model_proof_not_app_apply"

_FORBIDDEN_ALL = [
    "app_state_mutation",
    "external_send",
    "provider_execution_without_receipt",
    "hidden_tool_execution",
    "claiming_proof_without_receipt",
]

_ROLES: list[dict] = [
    # ── 3B roles ────────────────────────────────────────────────────────────
    {
        "role_id": "3b_scout",
        "role_family": "3b",
        "model_tier": "3b",
        "role_name": "3B Scout",
        "allowed_inputs": ["prompt_text", "context_capsule", "slot_contract"],
        "allowed_outputs": ["candidate_artifact", "route_hint"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "3b_extractor",
        "role_family": "3b",
        "model_tier": "3b",
        "role_name": "3B Extractor",
        "allowed_inputs": ["prompt_text", "context_capsule", "artifact_lens"],
        "allowed_outputs": ["extracted_candidate", "slot_fill_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "3b_classifier",
        "role_family": "3b",
        "model_tier": "3b",
        "role_name": "3B Classifier",
        "allowed_inputs": ["prompt_text", "context_capsule"],
        "allowed_outputs": ["classification_candidate", "label_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "3b_router",
        "role_family": "3b",
        "model_tier": "3b",
        "role_name": "3B Router",
        "allowed_inputs": ["prompt_text", "seed_route", "field_selection"],
        "allowed_outputs": ["route_candidate", "route_hint"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "3b_slot_filler",
        "role_family": "3b",
        "model_tier": "3b",
        "role_name": "3B Slot Filler",
        "allowed_inputs": ["slot_contract", "gaptext", "context_capsule"],
        "allowed_outputs": ["slot_fill_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "3b_quick_critic",
        "role_family": "3b",
        "model_tier": "3b",
        "role_name": "3B Quick Critic",
        "allowed_inputs": ["candidate_artifact", "context_capsule"],
        "allowed_outputs": ["critic_candidate", "critique_score"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "3b_style_check",
        "role_family": "3b",
        "model_tier": "3b",
        "role_name": "3B Style Check",
        "allowed_inputs": ["candidate_artifact", "style_profile"],
        "allowed_outputs": ["style_check_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "3b_refusal_boundary_check",
        "role_family": "3b",
        "model_tier": "3b",
        "role_name": "3B Refusal Boundary Check",
        "allowed_inputs": ["candidate_artifact", "context_capsule"],
        "allowed_outputs": ["boundary_check_candidate", "refusal_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    # ── 7B/8B roles ─────────────────────────────────────────────────────────
    {
        "role_id": "7b_writer",
        "role_family": "7b",
        "model_tier": "7b",
        "role_name": "7B Writer",
        "allowed_inputs": ["prompt_text", "context_capsule", "slot_contract", "gaptext"],
        "allowed_outputs": ["written_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "7b_synthesizer",
        "role_family": "7b",
        "model_tier": "7b",
        "role_name": "7B Synthesizer",
        "allowed_inputs": ["candidate_artifact", "context_capsule", "projection_set"],
        "allowed_outputs": ["synthesized_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "7b_planner",
        "role_family": "7b",
        "model_tier": "7b",
        "role_name": "7B Planner",
        "allowed_inputs": ["prompt_text", "context_capsule", "work_context"],
        "allowed_outputs": ["plan_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "7b_repo_reasoner",
        "role_family": "7b",
        "model_tier": "7b",
        "role_name": "7B Repo Reasoner",
        "allowed_inputs": ["repo_context", "context_capsule", "artifact_lens"],
        "allowed_outputs": ["repo_reasoning_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "7b_candidate_composer",
        "role_family": "7b",
        "model_tier": "7b",
        "role_name": "7B Candidate Composer",
        "allowed_inputs": ["projection_set", "slot_contract", "gaptext", "context_capsule"],
        "allowed_outputs": ["composed_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "7b_refiner",
        "role_family": "7b",
        "model_tier": "7b",
        "role_name": "7B Refiner",
        "allowed_inputs": ["candidate_artifact", "critique_score", "context_capsule"],
        "allowed_outputs": ["refined_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "7b_complex_critic",
        "role_family": "7b",
        "model_tier": "7b",
        "role_name": "7B Complex Critic",
        "allowed_inputs": ["candidate_artifact", "context_capsule", "projection_set"],
        "allowed_outputs": ["complex_critique_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    # ── Hybrid roles ─────────────────────────────────────────────────────────
    {
        "role_id": "hybrid_3b_scout_7b_synthesize_3b_check",
        "role_family": "hybrid",
        "model_tier": "hybrid",
        "role_name": "Hybrid 3B Scout → 7B Synthesize → 3B Check",
        "allowed_inputs": ["prompt_text", "context_capsule", "slot_contract"],
        "allowed_outputs": ["hybrid_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "hybrid_3b_extract_7b_compose_3b_boundary_critic",
        "role_family": "hybrid",
        "model_tier": "hybrid",
        "role_name": "Hybrid 3B Extract → 7B Compose → 3B Boundary Critic",
        "allowed_inputs": ["prompt_text", "context_capsule", "artifact_lens", "slot_contract"],
        "allowed_outputs": ["hybrid_candidate", "boundary_check_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "hybrid_7b_draft_3b_slot_check_7b_refine",
        "role_family": "hybrid",
        "model_tier": "hybrid",
        "role_name": "Hybrid 7B Draft → 3B Slot Check → 7B Refine",
        "allowed_inputs": ["prompt_text", "context_capsule", "slot_contract", "gaptext"],
        "allowed_outputs": ["hybrid_candidate", "refined_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "hybrid_no_model_precompute_3b_route_7b_candidate_final_gate",
        "role_family": "hybrid",
        "model_tier": "hybrid",
        "role_name": "Hybrid No-Model Precompute → 3B Route → 7B Candidate → Final Gate",
        "allowed_inputs": ["work_context", "precompute_result", "context_capsule"],
        "allowed_outputs": ["hybrid_candidate", "final_gate_result"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    # ── No-model roles ───────────────────────────────────────────────────────
    {
        "role_id": "schema_validation",
        "role_family": "no_model",
        "model_tier": "no_model",
        "role_name": "Schema Validation",
        "allowed_inputs": ["any_packet"],
        "allowed_outputs": ["validation_result"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "manifest_binding_validation",
        "role_family": "no_model",
        "model_tier": "no_model",
        "role_name": "Manifest Binding Validation",
        "allowed_inputs": ["manifest", "binding_spec"],
        "allowed_outputs": ["validation_result"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "cache_fingerprint_lookup",
        "role_family": "no_model",
        "model_tier": "no_model",
        "role_name": "Cache Fingerprint Lookup",
        "allowed_inputs": ["work_context", "cache_key"],
        "allowed_outputs": ["cache_lookup_result"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "slot_preparation",
        "role_family": "no_model",
        "model_tier": "no_model",
        "role_name": "Slot Preparation",
        "allowed_inputs": ["slot_contract", "work_context"],
        "allowed_outputs": ["prepared_slots"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "rule_based_refusal",
        "role_family": "no_model",
        "model_tier": "no_model",
        "role_name": "Rule-Based Refusal",
        "allowed_inputs": ["work_context", "context_capsule"],
        "allowed_outputs": ["refusal_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "deterministic_candidate_shape",
        "role_family": "no_model",
        "model_tier": "no_model",
        "role_name": "Deterministic Candidate Shape",
        "allowed_inputs": ["work_context", "slot_contract"],
        "allowed_outputs": ["shaped_candidate"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
    {
        "role_id": "trace_receipt_construction",
        "role_family": "no_model",
        "model_tier": "no_model",
        "role_name": "Trace Receipt Construction",
        "allowed_inputs": ["work_id", "spine_id"],
        "allowed_outputs": ["trace_ref", "receipt_ref"],
        "forbidden_actions": list(_FORBIDDEN_ALL),
        "authority_limit": "candidate_only_no_apply",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
    },
]

_ROLE_INDEX: dict[str, dict] = {r["role_id"]: r for r in _ROLES}


def get_model_role(role_id: str) -> dict:
    """Return role dict for the given role_id, or empty dict if not found."""
    return dict(_ROLE_INDEX.get(role_id, {}))


def list_model_roles() -> list[dict]:
    """Return all model roles."""
    return [dict(r) for r in _ROLES]


def list_roles_by_tier(tier: str) -> list[dict]:
    """Return all roles matching the given model_tier."""
    return [dict(r) for r in _ROLES if r["model_tier"] == tier]
