"""Odin Semantic Kernel IR — defines kernel IR objects.

Claim boundary: semantic_kernel_closure_compiles_odin_kernel_ir_not_runtime_completion
candidate_only: true
"""
from __future__ import annotations

CLAIM_BOUNDARY = "semantic_kernel_closure_compiles_odin_kernel_ir_not_runtime_completion"

NOT_PROVEN = [
    "production_readiness",
    "live_model_inference",
    "app_state_mutation",
    "external_send_authority",
]

_IR_OBJECTS = [
    {
        "ir_id": "UniversalWorkIR",
        "ir_name": "Universal Work IR",
        "description": "Top-level work request that enters the Odin pipeline.",
        "input_fields": ["input_text", "seed_pack", "pattern_mine", "caller_manifest"],
        "output_fields": ["work_capsule", "route_hint", "candidate_only"],
        "repo_artifact": "odin/universal_work/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send", "model_inference"],
        "claim_boundary": "universal_work_ir_candidate_only_no_app_apply",
        "not_proven": NOT_PROVEN,
    },
    {
        "ir_id": "ContextIR",
        "ir_name": "Context IR",
        "description": "Distilled context capsule from input and seed.",
        "input_fields": ["work_capsule", "seed_pack"],
        "output_fields": ["context_capsule", "field_selection", "candidate_only"],
        "repo_artifact": "odin/worklets/",
        "status": "partial",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "context_ir_partial_structural_evidence",
        "not_proven": NOT_PROVEN,
    },
    {
        "ir_id": "ArtifactLensIR",
        "ir_name": "Artifact Lens IR",
        "description": "Lens that projects context onto artifact views.",
        "input_fields": ["context_capsule", "artifact_type"],
        "output_fields": ["artifact_view", "lens_score", "candidate_only"],
        "repo_artifact": "odin/worklets/",
        "status": "partial",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "artifact_lens_ir_partial_structural_evidence",
        "not_proven": NOT_PROVEN,
    },
    {
        "ir_id": "SlotIR",
        "ir_name": "Slot IR",
        "description": "Slot contract for structured output binding.",
        "input_fields": ["slot_class", "slot_constraints"],
        "output_fields": ["slot_contract", "slot_evidence", "candidate_only"],
        "repo_artifact": "odin/slots/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "slot_ir_candidate_only_structural_evidence",
        "not_proven": NOT_PROVEN,
    },
    {
        "ir_id": "GaptextIR",
        "ir_name": "Gaptext IR",
        "description": "Gap text compiler for structured prompt filling.",
        "input_fields": ["seed_pack", "pattern_mine", "gap_fields"],
        "output_fields": ["gaptext_output", "gap_evidence", "candidate_only"],
        "repo_artifact": "odin/seeds/",
        "status": "partial",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "gaptext_ir_partial_structural_evidence",
        "not_proven": NOT_PROVEN,
    },
    {
        "ir_id": "ModelWorkIR",
        "ir_name": "ModelWork IR",
        "description": "ModelWorkPacket — structured work ready for model or deterministic route.",
        "input_fields": ["work_capsule", "context_capsule", "slot_contract"],
        "output_fields": ["model_work_packet", "route_hint", "candidate_only"],
        "repo_artifact": "odin/operational_spine/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send", "model_inference_without_receipt"],
        "claim_boundary": "model_work_ir_candidate_only_structural_evidence",
        "not_proven": NOT_PROVEN,
    },
    {
        "ir_id": "RouteIR",
        "ir_name": "Route IR",
        "description": "Route selector — small-model or deterministic route plan.",
        "input_fields": ["model_work_packet", "route_hint"],
        "output_fields": ["route_plan", "route_evidence", "candidate_only"],
        "repo_artifact": "odin/operational_spine/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "route_ir_candidate_only_structural_evidence",
        "not_proven": NOT_PROVEN,
    },
    {
        "ir_id": "ProviderReceiptIR",
        "ir_name": "Provider Receipt IR",
        "description": "Receipt from local provider execution (host-scoped, disabled by default).",
        "input_fields": ["provider_id", "prompt", "allow_local_provider_execution"],
        "output_fields": ["provider_receipt", "execution_performed", "candidate_only"],
        "repo_artifact": "odin/local_provider_receipts/",
        "status": "host_scoped_local_receipt_path",
        "evidence_class": "host_scoped_local_receipt",
        "forbidden_authority": ["app_apply", "external_send", "live_inference_without_flag"],
        "claim_boundary": "local_provider_receipt_harness_scoped_local_receipts_not_quality_benchmark",
        "not_proven": NOT_PROVEN,
    },
    {
        "ir_id": "CriticIR",
        "ir_name": "Critic IR",
        "description": "Critic cascade — deterministic + optional model critic. Advisory only.",
        "input_fields": ["candidate", "critic_config"],
        "output_fields": ["critic_packet", "critic_score", "not_authority", "candidate_only"],
        "repo_artifact": "odin/critic_runtime/",
        "status": "implemented_candidate_only",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send", "final_authority"],
        "claim_boundary": "critic_ir_candidate_only_advisory_not_authority",
        "not_proven": NOT_PROVEN,
    },
    {
        "ir_id": "CandidateIR",
        "ir_name": "Candidate IR",
        "description": "Candidate artifact — output of model/deterministic route, pre-final-gate.",
        "input_fields": ["response", "provider_receipt", "critic_packet"],
        "output_fields": ["candidate_artifact", "candidate_only", "app_apply"],
        "repo_artifact": "odin/packets/",
        "status": "partial",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "candidate_ir_candidate_only_no_app_apply",
        "not_proven": NOT_PROVEN,
    },
    {
        "ir_id": "ResponseIR",
        "ir_name": "Response IR",
        "description": "Response packet — structured output ready for app-owned apply decision.",
        "input_fields": ["candidate_artifact", "final_gate_result"],
        "output_fields": ["response_packet", "candidate_only", "app_apply"],
        "repo_artifact": "odin/packets/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "response_ir_candidate_only_no_app_apply",
        "not_proven": NOT_PROVEN,
    },
    {
        "ir_id": "FinalGateIR",
        "ir_name": "Final Gate IR",
        "description": "Final gate — checks candidate before returning to app.",
        "input_fields": ["candidate_artifact", "gate_config"],
        "output_fields": ["gate_result", "gate_evidence", "candidate_only"],
        "repo_artifact": "odin/execution_gate/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "final_gate_ir_candidate_only_structural_evidence",
        "not_proven": NOT_PROVEN,
    },
    {
        "ir_id": "ReceiptIR",
        "ir_name": "Receipt IR",
        "description": "Trace/receipt — links pipeline stages to evidence.",
        "input_fields": ["stage_outputs", "claim_boundary"],
        "output_fields": ["receipt", "trace", "not_proven"],
        "repo_artifact": "odin/proof_chain/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "receipt_ir_candidate_only_structural_evidence",
        "not_proven": NOT_PROVEN,
    },
    {
        "ir_id": "ClaimIR",
        "ir_name": "Claim IR",
        "description": "Claim classifier — safe wording for release claims.",
        "input_fields": ["claim_text", "evidence_refs", "evidence_class"],
        "output_fields": ["classification", "safe_wording", "allowed", "not_proven"],
        "repo_artifact": "odin/claims_compiler/",
        "status": "not_repo_real_yet",
        "evidence_class": "target_only",
        "forbidden_authority": ["release_certification", "security_certification", "production_readiness_claim"],
        "claim_boundary": "claim_ir_compiler_v0_not_certification",
        "not_proven": NOT_PROVEN,
    },
    {
        "ir_id": "SemanticBusEventIR",
        "ir_name": "Semantic Bus Event IR",
        "description": "Semantic bus event — local coordination signal.",
        "input_fields": ["channel", "kind", "source", "payload"],
        "output_fields": ["bus_event", "local_only", "candidate_only"],
        "repo_artifact": "odin/semantic_bus/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send", "public_network"],
        "claim_boundary": "semantic_bus_event_ir_local_only_no_public_network",
        "not_proven": NOT_PROVEN,
    },
    {
        "ir_id": "AgentHandoffIR",
        "ir_name": "Agent Handoff IR",
        "description": "Thor handoff compiler — work packet for agent operator.",
        "input_fields": ["objective", "repo_evidence", "allowed_edits", "forbidden_edits", "acceptance_gates"],
        "output_fields": ["handoff_bundle", "thor_runtime_execution", "agent_autonomy", "candidate_only"],
        "repo_artifact": "odin/thor_handoff_compiler/",
        "status": "implemented_candidate_only",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["agent_autonomy", "app_apply", "thor_runtime_execution"],
        "claim_boundary": "agent_handoff_ir_compiles_packets_not_agent_autonomy",
        "not_proven": NOT_PROVEN,
    },
]


def build_odin_work_ir(
    *,
    generated_at_utc: str = "2026-01-01T00:00:00Z",
) -> dict:
    """Build Odin kernel IR object list."""
    return {
        "artifact_kind": "odin_semantic_kernel_ir",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
        "generated_at_utc": generated_at_utc,
        "ir_object_count": len(_IR_OBJECTS),
        "ir_objects": _IR_OBJECTS,
        "not_proven": NOT_PROVEN,
    }
