"""Odin Semantic Kernel Pipeline — defines pipeline stages.

Claim boundary: semantic_kernel_closure_compiles_odin_kernel_ir_not_runtime_completion
candidate_only: true
"""
from __future__ import annotations

CLAIM_BOUNDARY = "semantic_kernel_closure_compiles_odin_kernel_ir_not_runtime_completion"

NOT_PROVEN = [
    "production_readiness",
    "live_model_inference",
    "app_state_mutation",
    "external_send_authority",
]

_STAGES = [
    {
        "stage_id": "universal_work",
        "stage_name": "Universal Work",
        "input_contract": "UniversalWorkInput",
        "output_contract": "UniversalWorkIR",
        "repo_artifact": "odin/universal_work/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "universal_work_stage_candidate_only",
        "not_proven": NOT_PROVEN,
    },
    {
        "stage_id": "context_capsule",
        "stage_name": "Context Capsule / ContextIR",
        "input_contract": "UniversalWorkIR",
        "output_contract": "ContextIR",
        "repo_artifact": "odin/worklets/",
        "status": "partial",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "context_capsule_stage_partial",
        "not_proven": NOT_PROVEN,
    },
    {
        "stage_id": "artifact_lens",
        "stage_name": "Artifact Lens",
        "input_contract": "ContextIR",
        "output_contract": "ArtifactLensIR",
        "repo_artifact": "odin/worklets/",
        "status": "partial",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "artifact_lens_stage_partial",
        "not_proven": NOT_PROVEN,
    },
    {
        "stage_id": "slot_contract",
        "stage_name": "Slot Contract",
        "input_contract": "ArtifactLensIR",
        "output_contract": "SlotIR",
        "repo_artifact": "odin/slots/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "slot_contract_stage_candidate_only",
        "not_proven": NOT_PROVEN,
    },
    {
        "stage_id": "gaptext",
        "stage_name": "Gaptext",
        "input_contract": "SlotIR",
        "output_contract": "GaptextIR",
        "repo_artifact": "odin/seeds/",
        "status": "partial",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "gaptext_stage_partial",
        "not_proven": NOT_PROVEN,
    },
    {
        "stage_id": "modelworkpacket",
        "stage_name": "ModelWorkPacket",
        "input_contract": "GaptextIR + ContextIR",
        "output_contract": "ModelWorkIR",
        "repo_artifact": "odin/operational_spine/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send", "model_inference_without_receipt"],
        "claim_boundary": "modelworkpacket_stage_candidate_only",
        "not_proven": NOT_PROVEN,
    },
    {
        "stage_id": "small_model_route",
        "stage_name": "Small Model Route",
        "input_contract": "ModelWorkIR",
        "output_contract": "RouteIR",
        "repo_artifact": "odin/operational_spine/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "small_model_route_stage_candidate_only",
        "not_proven": NOT_PROVEN,
    },
    {
        "stage_id": "provider_receipt",
        "stage_name": "Provider Receipt / Deterministic Route",
        "input_contract": "RouteIR",
        "output_contract": "ProviderReceiptIR",
        "repo_artifact": "odin/local_provider_receipts/",
        "status": "host_scoped_local_receipt_path",
        "evidence_class": "host_scoped_local_receipt",
        "forbidden_authority": ["app_apply", "external_send", "live_inference_without_flag"],
        "claim_boundary": "provider_receipt_stage_host_scoped_disabled_by_default",
        "not_proven": NOT_PROVEN,
    },
    {
        "stage_id": "critic_runtime",
        "stage_name": "Critic Runtime",
        "input_contract": "ProviderReceiptIR + CandidateIR",
        "output_contract": "CriticIR",
        "repo_artifact": "odin/critic_runtime/",
        "status": "implemented_candidate_only",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send", "final_authority"],
        "claim_boundary": "critic_runtime_stage_advisory_not_authority",
        "not_proven": NOT_PROVEN,
    },
    {
        "stage_id": "candidate_artifact",
        "stage_name": "Candidate Artifact",
        "input_contract": "CriticIR + ProviderReceiptIR",
        "output_contract": "CandidateIR",
        "repo_artifact": "odin/packets/",
        "status": "partial",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "candidate_artifact_stage_candidate_only",
        "not_proven": NOT_PROVEN,
    },
    {
        "stage_id": "response_packet",
        "stage_name": "Response Packet",
        "input_contract": "CandidateIR",
        "output_contract": "ResponseIR",
        "repo_artifact": "odin/packets/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "response_packet_stage_candidate_only",
        "not_proven": NOT_PROVEN,
    },
    {
        "stage_id": "final_gate",
        "stage_name": "Final Gate",
        "input_contract": "ResponseIR",
        "output_contract": "FinalGateIR",
        "repo_artifact": "odin/execution_gate/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "final_gate_stage_candidate_only",
        "not_proven": NOT_PROVEN,
    },
    {
        "stage_id": "trace_receipt_claim",
        "stage_name": "Trace / Receipt / Claim",
        "input_contract": "FinalGateIR",
        "output_contract": "ReceiptIR + ClaimIR",
        "repo_artifact": "odin/proof_chain/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["app_apply", "external_send"],
        "claim_boundary": "trace_receipt_claim_stage_candidate_only",
        "not_proven": NOT_PROVEN,
    },
    {
        "stage_id": "app_owned_apply_boundary",
        "stage_name": "App-owned Apply Boundary",
        "input_contract": "ReceiptIR + ResponseIR",
        "output_contract": "AppDecision (app-owned, outside Odin)",
        "repo_artifact": "odin/release_boundaries/",
        "status": "implemented_structural_evidence",
        "evidence_class": "structural_evidence",
        "forbidden_authority": ["odin_apply", "odin_external_send"],
        "claim_boundary": "app_owned_apply_boundary_odin_cannot_apply",
        "not_proven": NOT_PROVEN,
    },
]


def build_semantic_kernel_pipeline(
    *,
    generated_at_utc: str = "2026-01-01T00:00:00Z",
) -> dict:
    """Build semantic kernel pipeline."""
    return {
        "artifact_kind": "odin_semantic_kernel_pipeline",
        "candidate_only": True,
        "claim_boundary": CLAIM_BOUNDARY,
        "generated_at_utc": generated_at_utc,
        "stage_count": len(_STAGES),
        "stages": _STAGES,
        "not_proven": NOT_PROVEN,
    }
